### ISSUE TITLE
Data not being passed by context

### ISSUE THREAD

**Issue by samis-dv** [directus/gatsby-source#120]
### Describe the bug

When creating a page using createPage the data that is put into context is not passed through. An example of my code and error are
gatsby-node.js file

```
createPage({
          path: `/about/${teamType.team_type_slug}`,
          component: path.resolve('./src/pages/teams.tsx'),
          context: {
            // Used as a query argument in the component below
            name: "staff",
          },
        }); 
```
teams.tsx file
```
export const pageQuery = graphql`
  query($name: String!) {
    teamMembers: allDirectusTeamMember(filter: { team_member_type: { team_type_name: { eq: $name } } }) {
      nodes {
        directusId
        team_first_name
        team_job_title
        team_last_name
        team_bio
        team_photo {
          data {
            full_url
          }
        }
      }
    }
  }
`;
```
Then when I build the graphql
`Errors: Variable "$name" of required type "String!" was not provided.`

### Environment information

- **@directus/gatsby-dource-directus version**: ^0.2.6
- **Directus version**: 8.6.2
- **Gatsby version**: ^2.18.12
### To Reproduce

1. Setup gastby node file to create a page
2. In the function of createPage send some static data through context
3. Try to access the data in your query 

### Expected behavior

I expected $name to have the value staff

**Comment by loganwishartcraig** [comment]
Hey,

Not entirely sure this is related to the plugin yet - it seems like it may be more related to how the `teams` component is being consumed in your app.

As a sanity check, have you tested the query in the graphiql explorer? 

I think what may be happening is the `teams` component is used somewhere else in your app (outside of `gatsby-node.js`) and its not being provided any context. 

All this plugin does is populate the graphql data, so if your graphiql test returns data, the plugin should be working normally and it's likely something elsewhere.

Let me know.

**Comment by samis-dv** [comment]
@loganwishartcraig  Yes I copied I checked this query in the graphql explorer and I am even running it on my page if I dont pass in the data it works fine and returns everything. 

Also for sanity check I have a separate graphql query running on a different pafe and tried to pass in a number for limit (10) but it stopped working as soon as I tried to pass data and threw the same error about data not being passed.

**Comment by loganwishartcraig** [comment]
Ah, I think the problem is your component `teams.tsx` is located in the `pages/` directory.

All components in `pages/` get processed by gatsby automatically and no context is provided when gatsby processes them. That's why the query runs fine when no variables are used.

Try moving the `teams.tsx` out of the `pages/` directory and into to a new directory (e.g. `templates/`)

**Comment by loganwishartcraig** [comment]
See more here in the [gatsby docs](https://www.gatsbyjs.org/docs/gatsby-project-structure/#folders)

**Comment by samis-dv** [comment]
That worked maybe it should be in the readme, it wasn't super obvious this was the reason and I even asked on the Gatsby discord channel for help but nobody knew the answer and told me to change the plugin.
