### ISSUE TITLE
Runner.query is not a function

### ISSUE THREAD

**Issue by jacobrienstra** [directus/gatsby-source#13]
Hello! just upgraded to this from the old plugin and got this error: 

```
runner.query(...).then is not a function

  70 | 
  71 | module.exports.createPages = async ({ actions, graphql }) => {
> 72 |   const { data } = await graphql(`
     |                          ^
  73 |     query {
  74 |       allDataArticle {
  75 |         nodes {

File: gatsby-node.js:72:26



  TypeError: runner.query(...).then is not a function
  
  - graphql-runner.js:11 
    [satirev-gatsby]/[gatsby]/dist/bootstrap/graphql-runner.js:11:59
```

Help

**Comment by loganwishartcraig** [comment]
Hmm. Not sure what might cause that. Does it ocurr when you comment out the plguin config from ```gatsby-config.js``` or ```npm remove``` the plugin from the project? 

Looks like an error that might not be explicitly related to this plugin - just want to make sure.

**Comment by jacobrienstra** [comment]
Yeah that’s what I thought but when I switch to the old plugin (source directus cms) it goes away

**Comment by loganwishartcraig** [comment]
What does your ```gatsby-config.js``` look like?

The project actually has a deployment issue right now, Gatsby shouldn't even be loading the plugin.

Structurally, the [gatsby-source-directus-cms](https://github.com/loganwishartcraig/gatsby-source-directus-cms) plugin and this currently have no differences. The deprecation warning is to signal that future development will happen on this project.

**Comment by loganwishartcraig** [comment]
@jacobrienstra Just FYI - that deployment issue I mentioned has since been resolved. Should be able to install the plugin with no issues.

**Comment by jacobrienstra** [comment]
Ahh I bet that was it. Thank you!

**Comment by loganwishartcraig** [comment]
Fingers crossed - let us know if it's resolved!

**Comment by loganwishartcraig** [comment]
Gonna close this. Feel free to open another issue if it's not resolved.
