### ISSUE TITLE
Deploying to NPM

### ISSUE THREAD

**Issue by loganwishartcraig** [directus/gatsby-source#14]
@jooola Not sure how deployments to NPM work for this repo, can you advise? Saw a couple GitHub actions, but it doesn't seem like any of them include an active ```npm publish``` directive.

@rijkvanzanten you wouldn't know, would you?

**Comment by jooola** [comment]
Posting this just quick, I'm on vacation:
You need to use npm version command, to create a new version (patch/minor/major) (see the man page)

This will generate a Git tag and you can then push the tag to github. Github will then build test and publish the package to NPM.

Check the package.json file and try the following command : `npm run release -h` (not sure about the -h )

TLDR; `npm release patch && git push  && git push --tags`

**Comment by jooola** [comment]
And yeah sorry forgot to uncomment this task...

https://github.com/directus/gatsby-source/blob/master/.github/workflows/publish.yml#L35

**Comment by loganwishartcraig** [comment]
@jooola 

Thanks! 
Hope you have a good vacation :D

**Comment by jooola** [comment]
Ok, I shouldn't have tried to cut out a new release now, but I did it anyway... I'll document the process so that I'm not the only one making mistakes.

**Comment by jooola** [comment]
Fixed by 9af939f0bdd89d929396dea261afcc4f68bd6d06
