### ISSUE TITLE
gatsby-source & gatsby-plugin-sharp in graphql query

### ISSUE THREAD

**Issue by prKrumm** [directus/gatsby-source#156]
I am trying to use gatsby-image, gatsby-plugin-sharp (image processing) with the pictures uploaded from Directus.

similar to Gatsby-source-wordpress I would like to graphql query images like this:

`
query {
  api {
    projects {
      image {
        name
        url
        childImageSharp {
          fluid(width: 180, height: 180) {
            src
          }
        }
      }
    }
  }
}
`

**Comment by loganwishartcraig** [comment]
Hi,

Could you provide us with more info around your specific setup and what you've tried?

`gatsby-plugin-sharp` should be supported assuming you have it and `gatsby-transformer-sharp` installed. See more on their respective [docs pages](https://www.gatsbyjs.org/packages/gatsby-transformer-sharp/). Additionally, you should have the field set up in Directus using `file` or `files` interface, and only attach images as values. Lastly, there should be at least one record with at least one file attached for the field to show up in the graph.

Let us know.

**Comment by HashemKhalifa** [comment]
@prKrumm I think directus plugin has nothing to do with the image processing.

here is how I'm using the image component 

`import React from 'react'
import Img from 'gatsby-image'
import { graphql, useStaticQuery } from 'gatsby'

export const Image = ({ imgName, index, className }) => {
  const { allImageSharp } = useStaticQuery(
    graphql`
      query allTheImagesQuery {
        allImageSharp {
          edges {
            node {
              fluid(maxWidth: 1000) {
                ...GatsbyImageSharpFluid_withWebp_noBase64
                originalName
              }
            }
          }
        }
      }
    `
  )

  return allImageSharp.edges
    .filter(edge => edge.node.fluid.originalName === imgName)
    .map(myImage => (
      <Img className={className} key={index} fluid={myImage.node.fluid} />
    ))
}`

and here are the props you need
` <Image
                index={slider.directusId}
                imgName={image.filename_disk}
/>`

Hope it helps!

**Comment by loganwishartcraig** [comment]
Thanks for the added info @HashemKhalifa 

@prKrumm I'm going to close this - let us know if you're still having issues.
