### ISSUE TITLE
Support localization

### ISSUE THREAD

**Issue by juliosouza-pushstart** [directus/gatsby-source#16]
Is there any way to support field translations when using this source?

In the current state, we are required process the query result to merge the translated fields with the default one.

**Comment by juliosouza-pushstart** [comment]
For reference, https://www.gatsbyjs.org/packages/@fika/gatsby-source-cockpit/ does translations by joining the API results with a gatsby-config.js defined `languages` array.

When using that source, for every entry in a collection in the CMS, there are multiple nodes with a `lang` property in the GraphQL node list, one for each language, and an extra one for `any`. Filtering the nodes using the `lang` property is enough to select the desired language.

**Comment by loganwishartcraig** [comment]
Hey, @juliosouza-pushstart thanks for the suggestion.

Using the example schema from the docs ([here](https://docs.directus.io/guides/relationships.html#translations)), are you requesting we create a new ```article``` node for each related ```article_translation``` language, and merge the two entities fields?

**Comment by juliosouza-pushstart** [comment]
Yeah, that should work. Do you think that makes sense?

Also, this could be behind a toggle config, so we keep backwards compatibility.

**Comment by juliosouza-pushstart** [comment]
I believe that wouldn't work because translation entries are optional: 

Say we have a `fruit` collection with `name` text field and a `translation` field. In the `fruit_translation` collection, we also have a `name` text field. In this model, the translated name is optional, falling back to `fruit.name`.

**This is a query currently supported and its result:**

```graphql
query {
  allDirectusFruit {
    nodes {
      name
      translations {
        name
        language
      }
    }
  }
}
```

```json
{
  "data": {
    "allDirectusFruit": {
      "nodes": [
        {
          "name": "Apple",
          "translations": [
            {
              "name": "Manzana",
              "language": "es"
            },
            {
              "name": "Maçã",
              "language": "pt"
            }
          ]
        },
        {
          "name": "Banana",
          "translations": [
            {
              "name": "Plátano",
              "language": "es"
            }
          ]
        },
        {
          "name": "Strawberry",
          "translations": [
            {
              "name": "Fresa",
              "language": "es"
            },
            {
              "name": "Morango",
              "language": "pt"
            }
          ]
        }
      ]
    }
  }
}
```

Note that "Banana" doesn't have a translation for "pt", so it would use the default value from the `fruit` collection. Simply generating nodes for each entry in the translation collection would create these nodes:

* 3 entries for "Apple"
  * `{lang: "any", name: "Apple"}`
  * `{lang: "es", name: "Manzana"}`
  * `{lang: "pt", name: "Maçã"}`
* *2 entries for "Banana"*
  * `{lang: "any", name: "Banana"}`
  * `{lang: "es", name: "Plátano"}`
* 3 entries for "Strawberry"
  * `{lang: "any", name: "Strawberry"}`
  * `{lang: "es", name: "Fresa"}`
  * `{lang: "pt", name: "Morango"}`

So, if you run the query with a filter `{ lang: { eq: "any" }` (see below), it would return 3 results, but if you run it with ` { lang: { eq: "pt" }`, it would miss the "Banana" entry.

```graphql
query {
  allDirectusFruit(filter: { lang: { eq: "any" } }) {
    nodes {
      name
      translations {
        name
        language
      }
    }
  }
}
```

A similar issue would raise if you have some content that's translated into just ['en', 'pt'], and another that's translated in ['en', 'es', 'pt']. The developer creating the query would need to keep in mind if a content is translated and which languages are available.

My suggestion is to follow the model used by https://github.com/fikaproductions/fika-gatsby-source-cockpit where the available languages are defined in the gatsby config, so all collections have the translated entries available.

**Comment by loganwishartcraig** [comment]
I see what you mean about the ```banana``` record not showing up when the query is performed given that ```{ lang: { eq: "pt" }``` filter.

I'd be a bit hesitant to create separate nodes & a fallback for each translation in the plugin itself though. How would we source the data for the ```any``` translation in the event the child schema has no fields in common with it's parent? It also sort of "misrepresents" the way the data is actually stored in Directus (as well as returned through other methods like the native REST API). 

We could potentially think about adding a dummy ```{language: 'any'}``` translation (with no field values) to all translations. That would enable you to have a filter like ```(filter: { language: { in: ["en", "any"] } } )``` so parent records with no ```en``` translation still show up. 

The problem with that though is now you'd need to check each usage of the ```translation``` to ensure you're not consuming the dummy ```any``` translation.

Really what we want here is field level filters, which is currently an open issue gatsbyjs/gatsby#14060

**Comment by juliosouza-pushstart** [comment]
> It also sort of "misrepresents" the way the data is actually stored in Directus (as well as returned through other methods like the native REST API).

This is a fair concern. I'd favor API consistency over my original proposal.

That said, I'm not sure if any of the alternatives would help with seamlessly accessing translated fields as if they were part of the main object. It would still be necessary to have a utility function to process the result and merge the `translations` entry with its parent.

As a beginner with GraphQL, I feel this is a common pattern, to restructure the query output before using it in the application.

**Comment by loganwishartcraig** [comment]
Yeah, I mean I definitely see your point about it being cumbersome to have to apply additional processing to the data the query returns. However, I can't really think of a clean way to implement that functionality it in the plugin without altering the data Directus returns. It seems like something that needs to be supported at the query level (i.e. within Gatsby)

Hopefully the way your translations are set up in Directus is consistent enough to allow building some simple ```mergeLanguage``` helper function you could use across collections?

**Comment by juliosouza-pushstart** [comment]
Indeed! This is what we have in place for now 

```javascript
export const directusTranslations = (data, filterLanguage = 'any') => {
  return data.nodes.map((node) => {
    const { translations = [], ...data } = node;

    const translation = translations.find((t) => t.language === filterLanguage);
    const { language, ...translationData } = translation || {};

    return { ...data, ...translationData };
  });
};

```

**Comment by loganwishartcraig** [comment]
Awesome! I'm gonna close this for now - hopefully Gatsby will support field level filters soon.
