### ISSUE TITLE
childImageSharp support on images

### ISSUE THREAD

**Issue by Steven-Harris** [directus/gatsby-source#17]
Reopening issue [#19](https://github.com/Jonesus/gatsby-source-directus7/issues/19) from _Jonesus's_ repo. Basically, I have a collection with some text and images. I would like to use 
```
 query {
      allDirectusAboutUs {
        edges {
          node {
            description
            photo {
              childImageSharp {
                fluid(maxWidth: 500) {
                  ...GatsbyImageSharpFluid_withWebp
                }
              }
            }
            link
          }
        }
      }
    }
```

**Comment by loganwishartcraig** [comment]
Hey @Steven-Harris - thanks for this.

I'm hoping all you need to do is modify your query to use the ```localFile``` sub-field that should be attached to the ```photo``` field.

```
{
  allDirectusAboutUs {
    edges {
      node {
        description
        photo {
          localFile {
            childImageSharp {
              fluid(maxWidth: 500) {
                ...GatsbyImageSharpFluid_withWebp
              }
            }
          }
        }
        link
      }
    }
  }
}
```

This assumes you have not set ```downloadFiles``` to ```false``` in your ```gatsby-config.js```

Let us know if that solves your issue!

**Comment by Steven-Harris** [comment]
Awesome, thanks @loganwishartcraig! That got it!
