### ISSUE TITLE
Why do we use a custom logger ?

### ISSUE THREAD

**Issue by jooola** [directus/gatsby-source#18]
@loganwishartcraig Why do we use a custom logger ? Is that intended ?
Can't we use the default one ?

**Comment by loganwishartcraig** [comment]
The repo that inspired the plugin did it that way. It helps pre-format the log messages a bit, and I thought it might be nice in case we wanted to swap out loggers in the future.

Does Gatsby itself expose a logger, or would you suggest we just use ```console``` directly?

**Comment by jooola** [comment]
I think using console is the right way to do. Gatsby uses many loggers depending on the environment.

But gatsby uses something overkill, let's stick to our own dumb logger.
