### ISSUE TITLE
update doc to have /public/ in url

### ISSUE THREAD

**Issue by iryanrachman** [directus/gatsby-source#184]
i don't know why, but sometimes it may need to add public after the url maybe because of shared hosting. at least we know if it comes of to that in the doc

**Comment by loganwishartcraig** [comment]
Can you explain a little more? What URL?

**Comment by iryanrachman** [comment]
the api sir.. in the doc.. sometimes in the shared hosting we get example.com/public not like in the doc sir.. this can make the other confused for a moment.. so we should just add some explanation that we may have to add public after the url

**Comment by loganwishartcraig** [comment]
I think you might be posting in the wrong repo, this one is dedicated to the Gatsby source plugin, not the direcuts api. 

For the api in general, you might try posting here [@directus/api](https://github.com/directus/api) or maybe here [@directus/docs](https://github.com/directus/docs) to suggest changes to the documentation

**Comment by iryanrachman** [comment]
i am talking about gatsby source directus tho.. see ur config doc..

**Comment by loganwishartcraig** [comment]
Oh, I think I understand what you're saying. Are you saying we should add something the the configuration examples documentation that clarifies the 'url' property isn't always the servers origin?
