### ISSUE TITLE
why does my array not accepted by the server 

### ISSUE THREAD

**Issue by iryanrachman** [directus/gatsby-source#192]
i have tried to send a data using form... and i get stuck after trying to send array to the directus..
```fetch(url, {
    method: 'POST',
    headers: {
      'Accept': 'application/json',
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      nama: this.state.name,
      email: this.state.email,
      telepon: this.state.telepon,
      program: [1],
      tanggal_lahir: this.state.tanggal_lahir,
      tempat_lahir: this.state.tempat_lahir,
    })
})```

if i commented the program it works..

**Comment by loganwishartcraig** [comment]
Hi @iryanrachman 

I think you might be posting this issue in the wrong repo? If you're talking about the javascript sdk, try [@directus/sdk-js](https://github.com/directus/sdk-js). This repo is for the Gastby source plugin.
