### ISSUE TITLE
Files fail downloading on a slow internet connection without retry

### ISSUE THREAD

**Issue by ssijak** [directus/gatsby-source#197]
### Describe the bug

Files fail downloading on a slow internet connection. Files are normal images, no file larger then few megs. At some random file it just stops downloading and prints this for each file till the end : 
```
...
ERROR

error directus File will not be available through transforms.


 ERROR

error directus Failed to download remote file: https://dojo-directus.s3.amazonaws.com/uploads/0206b7d0-6123-41dc-8a39-6eb37e01acd3.jpg


 ERROR

error directus File will not be available through transforms.


 ERROR

error directus Failed to download remote file: https://dojo-directus.s3.amazonaws.com/uploads/c2a62457-c7f9-4486-9fe8-5cf4df306688.jpg


 ERROR

error directus File will not be available through transforms.


 ERROR

error directus Failed to download remote file: https://dojo-directus.s3.amazonaws.com/uploads/8569ec26-84f1-43da-9dee-2d7c5aba8786.jpg


 ERROR

error directus File will not be available through transforms.


 ERROR

error directus Failed to download remote file: https://dojo-directus.s3.amazonaws.com/uploads/4791a4d3-6f28-437c-8525-183b9ba279d7.jpg


 ERROR

error directus File will not be available through transforms.


 ERROR

error directus Failed to download remote file: https://dojo-directus.s3.amazonaws.com/uploads/42430dbc-dccc-49d6-92d3-b76ae5adcdf9.jpg
...
``` 

### Environment information

- **@directus/gatsby-dource-directus version**: 0.2.6
- **Directus version**: any
- **Gatsby version**: any

### To Reproduce

Start a project which downloads file from directus on slow internet connection

### Expected behavior

It should not happen, connection is not lost it is just slow (most easy way to reproduce is on a slower 4g connection). But even if the file could not be downloaded, there should be a configurable retry mechanism and timeout setting

**Comment by ssijak** [comment]
Digging through the source code I see that `gatsby-source-filesystem` is used to download the file and that library has retry and timeout limits stuck to some values. But, they can use the parameter for the number of concurent downloads `concurrent: process.env.GATSBY_CONCURRENT_DOWNLOAD || 200`. Setting this value to 20 seems to solve my problem on this connection. Maybe it is worth mentioning it in README somewhere.

**Comment by loganwishartcraig** [comment]
Nice, glad to hear you sorted it out. I agree we should mention we use gatsby-source-filesystem with a link to further customization.
