### ISSUE TITLE
Error while running the sourceNodes lifecycle

### ISSUE THREAD

**Issue by jf-home** [directus/gatsby-source#216]
Trying to run up a gatsby develop session and get the following message: 

"gatsby-source-directus" threw an error while running the sourceNodes lifecycle

### Environment information

- **@directus/gatsby-source-directus version** v0.0.44
- **Directus version**: v8.8.0
- **Gatsby version**: v2.24.7

### To Reproduce on Windows 10 (using Docker Desktop)

1. Install Docker Desktop application on Windows 10
2. Install and run the Directus Docker installation per the following instructions: 

     https://docs.directus.io/installation/docker.html

3. Install gatsby-source-directus plug-in in your Gatsby project
4. Reference the plug-in in your gatsby-config.js file (note: the user token can be obtained from the directus_users table in the MySQL database): 

    {
      resolve: `gatsby-source-directus`,
      options: {
        url: `localhost:8080`,
        protocol: 'http',
        project: '_',
        auth: {
          token: <YOUR_USER_TOKEN_IN_HERE>, 
        },
        targetStatuses: ['published', '__NONE__'],
        nameExceptions: {
          posts: "Article",
        },

5. Run `gatsby develop` from a terminal

### Expected behavior

Gatsby develop session should run without errors.  When complete content in Directus should be available through GraphQL (localhost:8000/___graphql).

### Output from the gatsby develop session: 

success open and validate gatsby-configs - 0.055s
success load plugins - 4.865s
success onPreInit - 0.033s
info One or more of your plugins have changed since the last time you ran Gatsby. As
a precaution, we're deleting your site's cache to ensure there's no stale data.     
success initialize cache - 0.117s
success copy gatsby files - 0.235s
success onPreBootstrap - 0.026s
success createSchemaCustomization - 0.016s
gatsby-source-directus Fetching Directus tables data...

 ERROR #11321  PLUGIN

"gatsby-source-directus" threw an error while running the sourceNodes lifecycle:

warn The gatsby-source-directus plugin has generated no Gatsby nodes. Do you need it?
success source and transform nodes - 0.340s
success building schema - 0.418s
success createPages - 0.003s
success createPagesStatefully - 0.141s
success updating schema - 0.044s
success write out redirect data - 0.010s
success Build manifest and related icons - 0.146s
success onPostBootstrap - 0.165s
info bootstrap finished - 13.738s
success onPreExtractQueries - 0.003s
success extract queries from components - 0.465s
success write out requires - 0.063s
success run static queries - 0.102s - 3/3 29.50/s
success run page queries - 0.031s - 6/6 195.75/s
success write out requires - 0.002s
⠀
You can now view gatsby-starter-default in the browser.

### gatsby info: 

  System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
  Binaries:
    Node: 12.14.1 - C:\Program Files\nodejs\node.EXE
    npm: 6.13.6 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.17
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gatsby: ^2.24.7 => 2.24.7
    gatsby-image: ^2.4.13 => 2.4.13
    gatsby-plugin-manifest: ^2.4.19 => 2.4.19
    gatsby-plugin-offline: ^3.2.19 => 3.2.19
    gatsby-plugin-react-helmet: ^3.3.10 => 3.3.10
    gatsby-plugin-sharp: ^2.6.20 => 2.6.20
    gatsby-source-directus: 0.0.44 => 0.0.44
    gatsby-source-filesystem: ^2.3.20 => 2.3.20
    gatsby-transformer-sharp: ^2.5.11 => 2.5.11
  npmGlobalPackages:
    gatsby-cli: 2.12.24

Thanks in advance for any assistance you're able to provide.

**Comment by jf-home** [comment]
I believe this is more of a Gatsby - Docker issue rather than a CMS-specific problem as I have also run into the same issue when running Cockpit as a Docker on my Windows 10 system as well.

**Comment by loganwishartcraig** [comment]
Gotcha, thanks for the report!

Did you manage to confirm if this is a Gatsby - Docker issue, or if it's localized to the plugin?
Happy to look into it more if you're only seeing this when using this plugin.

**Comment by loganwishartcraig** [comment]
Closed as "dependency issue"
