### ISSUE TITLE
Can't install with latest versions of node

### ISSUE THREAD

**Issue by cdanny358** [directus/gatsby-source#22]
`yarn add @directus/gatsby-source-directus` fails with the following error, with node 13.5.0 installed on my system:

`error @directus/sdk-js@6.0.1: The engine "node" is incompatible with this module. Expected version ">=8.0.0 <13.0.0". Got "13.5.0"`  
`error Found incompatible module.`

Any way around it, other than downgrading node? Ultimately I was hoping that `gatsby-source-graphql` would work directly with Directus 8, but no dice.

**Comment by loganwishartcraig** [comment]
Looks like we need to to upgrade a dependency.

Will release a hotfix for that as soon as we can. Thanks for letting us know!

**Comment by jooola** [comment]
See https://github.com/directus/sdk-js/pull/136

**Comment by jooola** [comment]
sdk-js 6.0.2 has been released with the fix.
