### ISSUE TITLE
Download Files fail

### ISSUE THREAD

**Issue by muhzulzidan** [directus/gatsby-source#239]
### Describe the bug

images or files are not downloaded, and not loaded, I am trying to get data from https://demo.directus.io/, and especially from the news collection, and there is an item that contains an image, but in gatsby, it is not shown, because it is not downloaded

### Environment information

- **@directus/gatsby-dource-directus version 0.2.9
- **Directus version the stable one ? 
- **Gatsby version 2.24.26
### To Reproduce

make gatsby new, add the plugin,  config it like this : 

```    {
      resolve: '@directus/gatsby-source-directus',
      options: {
        url: `${process.env.DIRECTUS_API_URL}`,
        project: 'thumper',
        auth: {
          email: `${process.env.DIRECTUS_USER}`,
          password: `${process.env.DIRECTUS_PASSWORD}`,
        },
        targetStatuses: ['published', 'draft', '__NONE__'],
        // blockCollections: [`ticket_notes`, `tickets`, `ticket_files`,  `mailing_list`, `products`,`locations`],
        allowCollections: [`news`, `news_relations`, `directus_files`],
      },
    },
```

### Expected behavior

it will work except the files, are not downloaded

**Comment by loganwishartcraig** [comment]
Hey! Thanks for the submission.

Could you elaborate a bit? Are you talking about images embedded into the `body` field - the WYSIWYG content? The WYSIWYG editor saves absolute URI's for images, so the paths for any downloaded files wont match whats saved by the WYSIWYG editor. This plugin downloads Directus files using `gatsby-source-filesystem` for use with other transform plugins anyway, not really for hosting purposes.

For what it's worth, it seems like the images referenced in their demo site news items don't exist anyway.

**Comment by muhzulzidan** [comment]
yeah just noticed that but what about the others files, it is not downloaded too.. 

we don't use it yet, but we might use it.

**Comment by loganwishartcraig** [comment]
What do you mean by "the other files aren't downloaded"?

Are they not available in the graphql layer? Are you expecting them to be downloaded at some specific location on your disk? 

Using your config I was able to query files normally, see below. Is something missing?
![image](https://user-images.githubusercontent.com/7434537/90168693-5321c400-dd52-11ea-9c15-660b8cf3f523.png)

**Comment by loganwishartcraig** [comment]
Hey - closing this as inactive. Feel free to open a new issue if needed.
