### ISSUE TITLE
Use yarn as default node package manager ?

### ISSUE THREAD

**Issue by jooola** [directus/gatsby-source#31]
@loganwishartcraig What do you think about this change ?

**Comment by loganwishartcraig** [comment]
Never used yarn personally, but I wouldn't have any issues with switching!

**Comment by jooola** [comment]
@rijkvanzanten I'd like to be consistent with the other Directus projects, do you have any preference/default for such tools ?

This isn't really a problem for me, but since I'm trying to build a good organization for this project, and in the long run export it to the other Directus projects I'd like to know which node package manager would be preferred ?

**Comment by rijkvanzanten** [comment]
I personally prefer Yarn over NPM 👍
