### ISSUE TITLE
Enhance documentation, reduce README size

### ISSUE THREAD

**Issue by jooola** [directus/gatsby-source#32]
I propose to move the code samples, and any advanced documentation in a /docs folder with smaller files. I feel like having everything in the `README` is really not easy to read/manage.

We need to structure the docs a bit more, so that it is browsable for those who seek for advanced configuration sample.

I might move the release documentation in its own file. So if newcomers search the docs it will be easy to find it with a `RELEASE.md` filename.

Maybe even build a small website that render our documentation (vuepress ?) using github pages, but we will need @rijkvanzanten approval and github page setup if we do this.
@loganwishartcraig Any thoughts ?

**Comment by rijkvanzanten** [comment]
Let's consider putting it as a guide on docs.directus.io if you wanna go the separate website route

**Comment by jooola** [comment]
I feel like having all the docs in a single README is hard to manage but handy for those who read the plugin doc on the [Gatsby plugins page](https://www.gatsbyjs.org/packages/@directus/gatsby-source-directus/?=@directus). It needs to be considered.

A work around could be to link the documentation to the github docs folder ?

**Comment by rijkvanzanten** [comment]
You can structure the main readme.md (used on the gatsby site) as a table of contents with links to the individual chapters that reside elsewhere

**Comment by loganwishartcraig** [comment]
Yeah - I think just splitting the current readme into separate pages would be nice, not sure we'd have the content volume to justify a separate statically generated site.

It might also be nice to rework the examples to work with the Directus demo site instead of the arbitrary data types I created?

**Comment by jooola** [comment]
@loganwishartcraig Yup, good point. First lets split the docs, then rewrite them to follow the demo data set.
