### ISSUE TITLE
Failed to fetch collections

### ISSUE THREAD

**Issue by stahldom** [directus/gatsby-source#36]
I'm pretty new Directus so this can be user error. 

Set up the Gatsby Starter on Local, as well as Directus on Local. Created a new collection, added two items and set it to public. I also set every system collection to public as well to be certain everything is accessible. 

My gatsby-config entry is: 
 ```
resolve: "@directus/gatsby-source-directus",
      options: {
        url: "localhost:8080",
        project: "mxc",
        targetStatuses: ["published", "__NONE__"],
        allowCollections: "blog",
      },
```

When starting ```gatsby develop```, I get the following error:

```
ERROR

error directus Failed to fetch collections


 ERROR

error directus Failed to build Directus nodes {
  e: APIError: Network error
      at new APIError (/Users/jeffstahlnecker/Developer/mxc-gatsby/node_modules/@directus/sdk-js/dist/cjs/API.js:41:28)
      at /Users/jeffstahlnecker/Developer/mxc-gatsby/node_modules/@directus/sdk-js/dist/cjs/API.js:261:23
      at processTicksAndRejections (internal/process/task_queues.js:94:5) {
    info: {
      error: [Error],
      url: '/collections',
      method: 'get',
      params: {},
      code: -1
    }
```

When checking directly, I'm able to to get collections from Directus. 

Assistance is appreciated.

**Comment by stahldom** [comment]
I installed a fresh version of Directus from git (the previous was Docker) and now it works fine. Are there some extra steps to take if we use the Docker container?

**Comment by jooola** [comment]
@stahldom Seems like the error was on the server side. I don't think there are any extra step when using docker, haven't used it though. So take my word with caution.

You error seems also really generic (network error), this might be a little mistake while setting up your server.

I suggest you to ask in the Directus community channel  https://directus.chat.

Closing this, reopen if you think it is needed.
