### ISSUE TITLE
Created a O2M relationship, deleted it again and now I get a warning

### ISSUE THREAD

**Issue by sondr3** [directus/gatsby-source#43]
### Describe the bug

During some testing I created a collection called `wat` where I created a O2M relation to the `users` collection, whatever I attempted didn't work and I deleted the field and the newly created junction collection. However, whenever I run `gatsby develop` now I get the following warning:

```text
warning directus Unable to resolve Directus junction. Missing junction information. {
  a: {
    id: 12,
    collection_many: 'directus_users',
    field_many: 'wat_id',
    collection_one: 'wat',
    field_one: 'peeps',
    junction_field: 'directus_files_id'
  },
  b: undefined
}
```

### Environment information

- **@directus/gatsby-dource-directus version**: `"@directus/gatsby-source-directus": "^0.2.4",`
- **Directus version**: `v8.6.1`
- **Gatsby version**: `"gatsby": "^2.19.19",`

### To Reproduce

1. Create a new collection.
2. Add a O2M relationship to the `directus_users`
3. Delete said relationship and the hidden junction collection
4. Warning appeared

### Expected behavior

No warning.

**Comment by jooola** [comment]
@sondr3 Thanks for the report, is the bug still present after cleaning gatsby cache ?

Could you try to run gatsby clean just after the bug raises ?

**Comment by sondr3** [comment]
Yeah, neither running `gatsby clean` or deleting `node_modules` and then reinstalling removes the message. Though I'm fairly certain this is a hickup from the server itself it's still mildly annoying as I've removed a bunch of other similar relationships but they don't give any warnings.

**Comment by jooola** [comment]
@sondr3 Ok, I'll try to reproduce this later.

We should search similar issues on directus/api before going too far on this one.

**Comment by loganwishartcraig** [comment]
This may be resulting from ditectus not completely cleaning up the internal ```directus_relations``` table when you remove a relation? I've experienced something similar with M2M like this [related issue](https://github.com/directus/api/issues/873)

Try checking that table manually, if the records corresponding to the deleted field is present, remove them manually. For a O2M relation I think there should only be one record.

Currently this plugin processes all relation records returned by the API. It has no additional logic to check if the relation is still "valid" and used by some collection. 

Let us know if you find anything in the ```directus_relations``` table

**Comment by loganwishartcraig** [comment]
Also, was this maybe a M2M relation rather than O2M?  The ```junction_field: 'directus_files_id'``` field makes me think it was a M2M. Would fit more with the issue I mentioned as well

**Comment by sondr3** [comment]
Might've been a M2M, I can't recall because I was doing a bunch of different testing at the time. But removing the rows manually in the `directus_relations` table made the warning go away, thanks! :smile:

**Comment by loganwishartcraig** [comment]
Great! Glad it worked out 😄
